import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">{children}
      <Toaster  toastOptions={{
    className: '',
    style: {
      border: '1px solid #fff',
      padding: '16px',
      color: '#fff',
      backgroundColor: '#000',
    },
  }} position="top-center" reverseOrder={false} />
      </body>
      
    </html>
  );
}
